#! /bin/bash
set -eu -o pipefail

if [[ $# -ne 1 ]] ; then
	echo "Usage: $0 FILE" 1>&2
	exit 1
fi

mimetype=$("${HOST_DIR}/bin/file" --mime-type --brief "$1")
case "${mimetype}" in
	application/x-executable | application/x-sharedlib)
		exit 0
		;;
	*)
		# Do nothing.
		exit 1
		;;
esac
